spring:
 application:
  name: capstone-user
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: ${EUREKA_SERVER_URL:http://localhost:8010/eureka}
 instance:
  hostname: ${INSTANCE_HOSTNAME:localhost}